### ISSUE TITLE
Is there an API (func call) for generating / parsing messages?

### ISSUE THREAD

**Issue by verdverm** [google/langfun#250]
The issue I see with libraries like this are that they wrap the actual call to the LLM. This means I cannot work it into my existing LLM pipelines, that I have to pass my API keys to yet another function call, and that my observability stack may or may not work.

It would be great if the library provided an API surface to simply create and parse the messages, letting us pass them to/from the LLM as we need. (i.e. unix philosophy of doing one small thing well and being able to chain together with other components)

**Comment by daiyip** [comment]
You can break down `lf.query` into 3 phases to integrate with your own LLM pipeline.

Example: 
```
import langfun as lf
import pyglove as pg

class Answer(pg.Object):
  result: int

# Phase 1: Get the raw prompt from structured input.
llm_prompt = lf.query_prompt('What is the result of 3 * 5?', Answer)

# Phase 2: Send the prompt to your own LLM and get a string response.
# NOTE: for inputs with multi-modal objects, instead of using the `.text` method, 
# you can prepare the inputs based on a list of chunks by calling via `llm_prompt.chunk()`)
llm_response = your_llm(llm_prompt.text)

# Phase 3: Reconstruct the structured output from the raw LLM response.
output_object = lf.query_output(llm_response, schema=Answer)
```

Alternatively, you could create a `lf.LanguageModel` subclass wrapping your LLM.
