### ISSUE TITLE
Implement litellm instead of different LLM inference classes

### ISSUE THREAD

**Issue by rachittshah** [google/langfun#296]
Suggestion:

Instead of having different packages for LLM inference, we can create a single litellm class which allows the user to use multiple LLMs and reduces dependency management. 

Happy to build this!

**Comment by daiyip** [comment]
Maybe [`lf.llms.REST`](https://github.com/google/langfun/blob/7d1ffeebbdb771c2dee3561fb58a3d8e327bfd34/langfun/core/llms/rest.py#L23) is the litellm you suggested?

Usage:
```
lm = lf.llms.REST(
   api_endpoint='https://fake-api.com/',
   request=lambda message, sampling_options: dict(
       model='test-model',
       prompt=message.text,
       temperature=0.0,
       top_k=0.1,
       top-p=0.2,
       stop_sequences=['\n'],
   ),
   result=lambda r: lf.LMSamplingResult(
       [lf.LMSample(c) for c in r['content']]),
   headers=dict(api_key='fake_key')
)
```

`REST` only depends on `requests`, also it supports subclassing. Please check out [`lf.llms.Authropic`](https://github.com/google/langfun/blob/7d1ffeebbdb771c2dee3561fb58a3d8e327bfd34/langfun/core/llms/anthropic.py#L86) and [`lf.llms.Groq`](https://github.com/google/langfun/blob/7d1ffeebbdb771c2dee3561fb58a3d8e327bfd34/langfun/core/llms/groq.py#L98) on how to subclass `lf.llms.REST`. We plan to migrate OpenAI and VertexAI models to REST in future.

Hopefully it helps.

**Comment by rachittshah** [comment]
Hey @daiyip, thanks for the reply!
